# Generated by Django 2.0.3 on 2018-04-25 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=15)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=15)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(default=None, max_length=150, null=True)),
                ('calificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConversacionPrivada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHora', models.DateTimeField(auto_created=True)),
                ('mensaje', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ConversacionPublica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraPregunta', models.DateTimeField(auto_created=True)),
                ('pregunta', models.CharField(max_length=150)),
                ('respuesta', models.CharField(default=None, max_length=150, null=True)),
                ('fechaHoraRespuesta', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbu', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('fechaDeVencimiento', models.DateField()),
                ('ccv', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoViaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
                ('fechaDeNacimiento', models.DateField(default=None, null=True)),
                ('dni', models.CharField(default=None, max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gasto_total', models.FloatField(default=0.0)),
                ('comentario', models.CharField(max_length=150)),
                ('origen', models.CharField(max_length=20)),
                ('destino', models.CharField(max_length=20)),
                ('fechaHoraSalida', models.DateTimeField()),
                ('duracion', models.IntegerField()),
                ('comision', models.FloatField(default=0.5)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unAventonApp.Auto')),
                ('cuentaBancaria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unAventonApp.CuentaBancaria')),
                ('tipoViaje', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='unAventonApp.TipoViaje')),
            ],
        ),
        migrations.CreateModel(
            name='ViajeCopiloto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraDeSolicitud', models.DateTimeField(auto_created=True)),
                ('estaConfirmado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Usuario')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Viaje')),
            ],
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='usuario',
            field=models.ManyToManyField(to='unAventonApp.Usuario'),
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Usuario'),
        ),
        migrations.AddField(
            model_name='conversacionpublica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Usuario'),
        ),
        migrations.AddField(
            model_name='conversacionpublica',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Viaje'),
        ),
        migrations.AddField(
            model_name='conversacionprivada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Usuario'),
        ),
        migrations.AddField(
            model_name='conversacionprivada',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Viaje'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='deUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Calificacion.deUsuario+', to='unAventonApp.Usuario'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='paraUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Usuario'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='viaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Viaje'),
        ),
        migrations.AddField(
            model_name='auto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='viajecopiloto',
            unique_together={('usuario', 'viaje')},
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('deUsuario', 'paraUsuario', 'viaje')},
        ),
    ]
