# Generated by Django 2.0.3 on 2018-05-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unAventonApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='entidad',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
