# Generated by Django 2.0.3 on 2018-05-30 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unAventonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='cbu',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='viajecopiloto',
            name='fecha_hora_de_solicitud',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 30, 0, 49, 9, 287814, tzinfo=utc)),
        ),
    ]
