# Generated by Django 2.0.3 on 2018-05-18 20:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unAventonApp', '0002_cuentabancaria_entidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='cuentaBancaria',
            new_name='cuenta_bancaria',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='fechaHoraSalida',
            new_name='fecha_hora_salida',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='tipoViaje',
        ),
        migrations.AddField(
            model_name='viaje',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='se_repite',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='viajecopiloto',
            name='fecha_del_viaje',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viajecopiloto',
            name='fecha_hora_de_solicitud',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 18, 20, 18, 18, 986596, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='comision',
            field=models.FloatField(default=0.05),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='duracion',
            field=models.FloatField(),
        ),
        migrations.RemoveField(
            model_name='viajecopiloto',
            name='fechaHoraDeSolicitud',
        ),
        migrations.AlterUniqueTogether(
            name='viajecopiloto',
            unique_together={('usuario', 'viaje', 'fecha_del_viaje')},
        ),
    ]
