# Generated by Django 2.0.3 on 2018-05-30 00:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unAventonApp', '0002_auto_20180530_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajecopiloto',
            name='fecha_hora_de_solicitud',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 30, 0, 54, 11, 711525, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='cuentabancaria',
            unique_together={('usuario', 'cbu')},
        ),
    ]
