# Generated by Django 2.0.3 on 2018-05-30 00:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unAventonApp', '0003_auto_20180530_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarjeta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='unAventonApp.Usuario'),
        ),
        migrations.AlterField(
            model_name='viajecopiloto',
            name='fecha_hora_de_solicitud',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 30, 0, 59, 54, 793943, tzinfo=utc)),
        ),
    ]
