# Generated by Django 2.0.3 on 2018-05-18 20:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('unAventonApp', '0003_auto_20180518_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viajecopiloto',
            name='fecha_hora_de_solicitud',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2018, 5, 18, 20, 57, 41, 677028, tzinfo=utc)),
        ),
    ]
