# Generated by Django 2.0.3 on 2018-06-13 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('unAventonApp', '0005_auto_20180530_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='auto_lugares_ocupados_de_antemano',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viajecopiloto',
            name='calificacion_a_copiloto',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='viajecopiloto',
            name='calificacion_a_copiloto_mensaje',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='viajecopiloto',
            name='calificacion_a_piloto',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='viajecopiloto',
            name='calificacion_a_piloto_mensaje',
            field=models.CharField(blank=True, default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='viajecopiloto',
            name='fecha_hora_de_solicitud',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
